export const quotes = [
    { quote: 'horkkamaiset huume piikit.', author: 'Elina Luoma-aho' },
    { quote: 'tämä on siis se kurssi, jolla ei kuole ihmisiä. ainakaan paljoa.', author: 'Ilkka Männikkö' },
    { quote: 'pitäkää huoli, että teillä on kavereita myös toisessa leirissä, jos joskus mennään kohti sisällissotaa.', author: 'Ilkka Männikkö'},
    { quote: 'Välttäkää sisällissotia ja hyökätkää mieluummin toisaalle, tulee vähemmän riesaa.', author: 'Ilkka Männikkö'},
    { quote: 'uusi sieni, juhlapäivä.', author: 'Hannu Sinisalo'},
    { quote: 'kaksi pointtia, mä en ole mikään alexander stubb.', author: 'Hannu Sinisalo'},
    { quote: 'joka kerta, kun muuttuja siirtyy integraalimerkin yli, jossain päin maailmaa kuolee kissanpentu.', author: 'Hannu Sinisalo'},
    { quote: 'hämmentävä magic vuorovaikutus.', author: 'Pasi Ahtola'},
    { quote: 'koska lahjattomia emme ole emmekä lahjattomiksi halua tulla... olkaamme siis harry pottereita.', author: 'Pasi Ahtola'},
    { quote: 'ominaisliike, mitä peppua', author: 'Pasi Ahtola'},
    { quote: 'jos järjestätte kolmenkimppoja kavereiden kanssa', author: 'Pasi Ahtola'},
    { quote: 'pitkän parisuhteen salaisuus on, että vie vaimon thaimaahan ja hakee sen kymmenen vuoden päästä.', author: 'Pasi Ahtola'},
    { quote: 'kukaan ei levitoi vaan se peppu osuu siihen puuhun ja se naula sattuu', author: 'Minna Saarinen'},
    { quote: 'ihmiset eivät yhteytä', author: 'Minna Saarinen'},
    { quote: 'ajattele itsesi kaasuksi', author: 'Minna Saarinen'},
    { quote: 'hmm, miten saada saariselta palkka pois', author: 'Minna Saarinen'},
    { quote: 'mieti itsesi pölyhiukkasena, miltä se näyttää', author: 'Minna Saarinen'},
    { quote: 'jos sen tekee oikein, niin ei sitä voi tehdä väärin.', author: 'Antti Moilanen'},
    { quote: 'tää on ihan hirvee tehtävä, pistetääs se.', author: 'Antti Moilanen'},
    { quote: 'kemialliset systeemit toimii niin kuin laiska ihminenkin eli vastustetaan muutosta. kuulostaa ihan suomalaiselta politiikaltakin.', author: 'Antti Moilanen'},
    { quote: 'opetelkaa laittamaan korkki kiinni. sopii ohjeeksi myös muutenkin.', author: 'Antti Moilanen'},
    { quote: 'onks äikän tunnilla ollu äsken jotain ihmeellistä ku suurin osa poissaolijoista on ollu kuitenkin viime tunnilla äikässä paikalla', author: 'Antti Moilanen'},
    { quote: 'pitäiskö perustaa suomen muumipuolue. pistettäis suomi kiinni marraskuusta huhtikuuhun ja pötköteltäis vaan.', author: 'Pasi Ahtola'},
    { quote: 'mikroskooppimoolinen kaukoputki', author: 'Pasi Ahtola'},
    { quote: 'olet kaunis ja hyvän tuoksuinen ihminen', author: 'Heikki Liuska'},
    { quote: 'venäjällä vodka tappaa enemmän miehiä kuin muualla. olisi kiinnostava nähdä, miten se vaikuttaa tähän.', author: 'Heikki Liuska'},
    { quote: 'liuskan perheen jäsenyys... se ois kyllä kaupan', author: 'Heikki Liuska'},
    { quote: 'sä olet vain yksi selkärankainen, etkä yhtään merkityksellisempi kuin muut selkärankaiset.', author: 'Elina Luoma-aho'},
    { quote: 'ajattele itseäsi hetkeksi nivelmatona ja taputtele niitä nivelmadon jäänteitä. ajattele olevasi osa suurta eliökuntaa.', author: 'Elina Luoma-aho'},
    { quote: 'pasi on vielä parempi kuin minä, mikä on tosi harvinaista', author: 'Elina Luoma-aho'},
    { quote: 'ja kurpitsansiemeniä eturauhaselle.', author: 'Hristo Popov'},
    { quote: 'ei-negatiivinen kuulostaa omaan korvaan paremmalta ku epänegatiivinen. ei siinä, toinen tykkää tyttärestä ja toinen äidistä', author: 'Emilia Rautiainen'},
    { quote: 'huolia murheita turhia toiveita.', author: 'Hannu Sinisalo'},
    { quote: 'vähä jännitti, kun rehtori meni tosta just ohi, kun sanottiin, että ei tällästä saa enää tehä, mutta me tehään.', author: 'Minna Saarinen'},
    { quote: 'mitä eroa on opettajalla ja rautanaulalla. mä tiiän et ei paljoo, mutta koittakaa nyt jotain keksiä.', author: 'Minna Saarinen'},
    { quote: 'what happens in kaksnollaysi stays in kaksnollaysi', author: 'Hannu Sinisalo'},
    { quote: 'siskonmakkara on mun lemppari lainasana. mutta tiedättekös, mikä se on ruotsiks', author: 'Hannu Sinisalo'},
    { quote: 'uskokaa mua, ollaan vielä ihan asiassa, mato-ongella ja teleskooppisarjalla on paljonkin yhteistä.', author: 'Hannu Sinisalo'},
    { quote: 'ehdimme mennä vielä helvettiin, ja sehän on teille ihan oikein', author: 'Mikko Turunen'},
    { quote: 'ja siellä tykin vessan seinässä luki, save me from anal. toisaalta siellä ehkä aiheellinen pelko.', author: 'Mikko Turunen'},
    { quote: 'diktatuurivaltiossa kirjat palaa, ja niin kohta myös ihmiset.', author: 'Mikko Turunen'},
    { quote: 'jos tuntuu, että et osaa ikinä kertoa kaverille mitään vastausta, niin ei hätää, tähänkin on ratkaisu. www.tredu.fi ja sieltä kohta opiskelijaksi.', author: 'Mikko Turunen'},
    { quote: 'mun ois vaikee ruoskia toista ihmistä, et ei lähtis ihan ykkösellä.', author: 'Jarkko Vilkkilä'},
    { quote: 'käynti clasussa vastaa louvressa vierailua.', author: 'Jarkko Vilkkilä'},
    { quote: 'jos olet vasemmistonuori, niin syvimmät osanottoni', author: 'Mikko Turunen'},
    { quote: 'älkää eläkö tän ikäsiks kun minä. sitte sattuu jokapaikkaan', author: 'Hannu Sinisalo'},
    { quote: 'ja tulemme törmäämään tähän n-sanaan useasti seuraavien tuntiemme aikana...', author: 'Ilkka Männikkö'},
    { quote: 'tää on niinkun laiton tää järjestelmä mikä meillä nyt on', author: 'Mari rauhala puhuuu OPKH:sta'},
    { quote: 'sää kyllä selkeesti meet kädelle sinne mut joo', author: 'Hristo Popov'},
    { quote: '', author: ''},
    { quote: '', author: ''}
]